config/routes.rb
Insarce2::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :aperos

    root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  
 user ||= User.new # guest user (not logged in)

   if user.persisted?
    can :read, Apero
    can :manage, Apero, :user_id => user.id
    else #guest ar not allowed
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/apero.rb
class Apero < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :category
  attr_accessible :category_id, :content, :date, :hour, :name, :user_id, :visibility
  
  validates :visibility, :presence => true
  validates :name, :presence => true
  validates :content, :presence => true
  validates :category_id, :numericality => { :less_than_or_equal_to => 3}
  validate :check_date
 

  def check_date
  	if date < Date.today
  		errors.add(:date, "can't be in the past")
  	end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :id, :name
end

app/controllers/aperos_controller.rb
class AperosController < ApplicationController
  # GET /aperos
  # GET /aperos.json
  before_filter :authenticate_user!, :except => [:index]
  load_and_authorize_resource
  def index
 
    @aperos = Apero.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aperos }
    end
  end

  # GET /aperos/1
  # GET /aperos/1.json
  def show
    @apero = Apero.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @apero }
    end
  end

  # GET /aperos/new
  # GET /aperos/new.json
  def new
    @apero = Apero.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @apero }
    end
  end

  # GET /aperos/1/edit
  def edit
    @apero = Apero.find(params[:id])
  end

  # POST /aperos
  # POST /aperos.json
  def create
    @apero = Apero.new(params[:apero])
	@apero.user_id = current_user.id

    respond_to do |format|
      if @apero.save
        format.html { redirect_to @apero, notice: 'Apero was successfully created.' }
        format.json { render json: @apero, status: :created, location: @apero }
      else
        format.html { render action: "new" }
        format.json { render json: @apero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aperos/1
  # PUT /aperos/1.json
  def update
    @apero = Apero.find(params[:id])

    respond_to do |format|
      if @apero.update_attributes(params[:apero])
        format.html { redirect_to @apero, notice: 'Apero was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aperos/1
  # DELETE /aperos/1.json
  def destroy
    @apero = Apero.find(params[:id])
    @apero.destroy

    respond_to do |format|
      format.html { redirect_to aperos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_url, :alert => exception.message

  	
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/aperos_helper.rb
module AperosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/aperos/_form.html.erb
<%= form_for(@apero) do |f| %>
  <% if @apero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apero.errors.count, "error") %> prohibited this apero from being saved:</h2>

      <ul>
      <% @apero.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :hour %><br />
    <%= f.time_select :hour %>
  </div>
  <div class="field">
    <%= f.label :visibility %><br />
    <%= f.text_field :visibility %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aperos/edit.html.erb
<h1>Editing apero</h1>

<%= render 'form' %>

<%= link_to 'Voir', @apero %> |
<%= link_to 'Retour', aperos_path %>

app/views/aperos/index.html.erb
<h1>Liste des soirées à venir</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Description</th>
    <th>Date</th>
    <th>Heure</th>
    <th>Créateur</th>
    <th>Visibilité</th>
    <th>Categorie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aperos.each do |apero| %>
  <tr>
    <td><%= apero.name %></td>
    <td><%= apero.content %></td>
    <td><%= apero.date %></td>
    <td><%= apero.hour %></td>
    <td><%= User.find(apero.user_id).email %></td>
    <td><%= apero.visibility %></td>
    <td><%= Category.find(apero.category_id).name %></td>
    <td><%= link_to 'Voir', apero %> </td>
    <td><% if can? :edit, apero %>
        <%= link_to 'Modifier', edit_apero_path(apero) %>
          <% end %>  </td>
    <td><% if can? :destroy, apero %>
        <%= link_to 'Détruire', apero, method: :delete, data: { confirm: 'Etes vous sûr?' } %>
          <% end %> 
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Créer un nouvel apéro', new_apero_path %>

app/views/aperos/new.html.erb
<h1>New apero</h1>

<%= render 'form' %>

<%= link_to 'retour', aperos_path %>

app/views/aperos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @apero.name %>
</p>

<p>
  <b>Content:</b>
  <%= @apero.content %>
</p>

<p>
  <b>Date:</b>
  <%= @apero.date %>
</p>

<p>
  <b>Hour:</b>
  <%= @apero.hour %>
</p>

<p>
  <b>User:</b>
  <%= User.find(@apero.user_id).email %>
</p>

<p>
  <b>Visibility:</b>
  <%= @apero.visibility %>
</p>

<p>
  <b>Category:</b>
  <%= Category.find(@apero.category_id).name %>
</p>

<% if can? :edit, @apero %>
<%= link_to 'Modifier', edit_apero_path(@apero) %> |
<% end %> 
<%= link_to 'Retour', aperos_path %>

app/views/home/index.html.erb
 <div class="span12">
<h1>Bienvenue sur INSAPERAVE </h1>
<p>Pour l'instant, AJOUTE DES PUTAINS D'EVENEMENTS</p>

<body>
Mais aussi s'authentifier si on veut
<%= link_to "Apero index", aperos_path %>
 </body>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aperaaavvvve</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="favicon.ico" rel="icon" type="image/x-icon" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>



<body>
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="<%= root_url %>">Insapéro</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="<%= aperos_path %>">Home</a></li>
              <li><a href="<%= new_apero_path %>">Créer un apéro</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              

    <% if user_signed_in? %>
     Signed in as <%= current_user.email %>. 
    <%= link_to "Log out", destroy_user_session_path %>
    <% else %>
    <%= link_to "S'enregistrer", new_user_registration_path %> or <%= link_to "Se connecter", new_user_session_path %>
    <% end %>

      </ul>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

  </div>
</div>


      <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <P align="center">
          <img src="http://test.thecorpo.fr/site/files/6513/6117/8539/header_page_soiree.jpg" height="500" width="1200" alt="">
          <div class="container">
            <div class="carousel-caption">
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <P align="center">
          <img src="http://banded.be/wp/wp-content/uploads/kompakt-beach-party-220608-header.jpg" height="500" width="1200" alt="">
          <div class="container">
            <div class="carousel-caption">
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              
            </div>
          </div>
        </div>
        <div class="item">
          <P align="center">
          <img src="http://www.dtweb.fr/actu/wp-content/uploads/2013/04/google.jpg" height="500" width="1200" alt="">
          <div class="container">
            <div class="carousel-caption">
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->


   <div class="container">
    <div class="row">
        <div class="span9"><%= yield %>
        </div>
      <div class="span3">
        <h2>About Us</h2>
        
      </div>
    </div>
  </div>



</body>
</html>